services:
  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "8501:8501"
  #   environment:
  #     - WATCHDOG_TIMEOUT=10
  #   depends_on:
  #     - backend
