services:
  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    command: streamlit run app.py
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    depends_on:
      - backend